Update .github/workflows/docker-publish.yml

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -40,6 +40,13 @@ jobs:
             done
           } | xargs -P $(grep -ce '^processor\s\+:' /proc/cpuinfo) -t -i bash -c '{}'
 
+      - name: Print the intermediate results
+        run: |
+          echo ">> succeeded: $(cat s.txt | wc -l)"
+          cat s.txt
+          echo ">> failed: $(cat f.txt | wc -l)"
+          cat f.txt
+
       - name: Clean up images
         run: |
           docker image ls -q | xargs docker image rm -f
@@ -52,12 +59,13 @@ jobs:
                 echo -ne "docker-compose build ${n} && docker-compose push ${n}"
                 echo -ne " && docker image ls -q ${{ github.actor }}/${n} | xargs docker image rm -f"
                 echo -ne " && echo '${n}' >> s.txt"
-                echo -e " && sed -ie '/^${n}$/d' f.txt"
+                echo -ne " && sed -ie '/^${n}$/d' f.txt"
+                echo -e ' || :'
               done
             } | xargs -P $(grep -ce '^processor\s\+:' /proc/cpuinfo) -t -i bash -c '{}'
           fi
 
-      - name: Print results
+      - name: Print the final results
         run: |
           echo ">> succeeded: $(cat s.txt | wc -l)"
           cat s.txt
